In [6]:
import numpy as np

In [7]:
op=np.genfromtxt(r"C:\Users\DELL\Downloads\train_extended.csv",delimiter=",",skip_header=1)

#  1.What is the max and min length

In [8]:
length=op[:,0]
np.max(length)

7.58349125

In [9]:
length=op[:,0]
np.min(length)

0.0

# 2.What is the difference between the max len and min len

In [10]:
np.max(length)-np.min(length)

7.58349125

# 3.Find the col wise avg

In [11]:
def f(x):
    return np.mean(x)
average=(np.apply_along_axis(f,0,op))
average

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

# 4.find out the age whose height is greater than 0.4

In [12]:
z=op[:,7].take(np.where(op[:,2]>0.4))
print(z.shape)
print(z)

(1, 55336)
[[11. 14. 13. ... 11. 11. 11.]]


# 5.What is the avg height and weight of the person whose age is 10

# 6.what is the total shell weight

In [20]:
ShellWeight=op[:,6]
np.sum(ShellWeight)

1326845.8295214002

# 7.how many persons belong to the each and unique age

In [27]:
Age=op[:,7]
np.unique(Age,return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

# 8.what is the difference stucked weight and the viscera weight 

In [28]:
shucked_weight=op[:,4]
viscera_weight=op[:,5]
difference=shucked_weight-viscera_weight
difference

array([5.9817445, 3.855532 , 4.1106775, ..., 2.9199985, 5.329706 ,
       9.8372765])

# 9.what is the avg height of the person whose age is b/w 14 and 19

In [14]:
k=op.take(np.where((op[:,7]>14) & (op[:,7]<19)))
sum=np.sum(k)
count=list(k.shape)
print("average height of the persons age is between 14 and 19 is ",np.round(sum/count[1]))

average height of the persons age is between 14 and 19 is  7.0


# 10.what is the avg weight if we include shucked weight viscera weight and shell weight

In [16]:
k=np.sum(op[:,3:7])
c=list(op.shape)
print("the average weight if we included shucked weight,viscara weight,and shell weight",k)

the average weight if we included shucked weight,viscara weight,and shell weight 8948043.333077429
